Repository nicanor-jay/Court-Transcript, pull requests merged in 2025-10, with the labels that each got.

#68 Add ECR Dashboard creation to Terraform phase one
  terraform/phase-one/main.tf
Labels: AWS, dashboard, terraform

#88 Terraform ESC task definition (dashboard)
  terraform/README.md
  terraform/main.tf
  terraform/phase-two/main.tf
  terraform/phase-two/variables.tf
  terraform/variables.tf
Labels: AWS, dashboard, terraform

#90 Terraform ECS service (dashboard)
  terraform/README.md
  terraform/main.tf
  terraform/phase-one/main.tf
  terraform/phase-one/variables.tf
  terraform/phase-two/main.tf
  terraform/phase-two/variables.tf
  terraform/variables.tf
Labels: AWS, dashboard, terraform

#100 Fix: handle multiple appointment date formats
  judge_scraping/judge_scraping.py
Labels: bug, enhancement

#107 added judges_rds.py
  database/schema.sql
  judge_scraping/README.MD
  judge_scraping/judge_scraping.py
  judge_scraping/judges_rds.py
  judge_scraping/rds_utils.py
  judge_scraping/requirements.txt
Labels: bug, enhancement

#112 Add judge names to metadata extraction
  pipeline/README.md
  pipeline/metadata_xml.py
  pipeline/test_metadata_xml.py
Labels: documentation, enhancement

#106 Add duplicate XML filter script
  pipeline/requirements.txt
  xml_extraction/README.md
  xml_extraction/conftest.py
  xml_extraction/get_unique_xml.py
  xml_extraction/metadata_xml.py
  xml_extraction/parse_xml.py
  xml_extraction/path_bootstrap_util.py
  xml_extraction/requirements.txt
  xml_extraction/test_metadata_xml.py
  xml_extraction/test_parse_xml.py
Labels: documentation, enhancement

#117 Update imports
  main.py
  test_main.py
  xml_extraction/get_unique_xml.py
  xml_extraction/path_bootstrap_util.py
Labels: enhancement

#124 Test make etl script
  case_fetcher/case_fetcher.py
  dashboard/rds_utils.py
  database/schema.sql
  gpt/summary.py
  judge_scraping/judge_scraper.py
  judge_scraping/judges_rds.py
  judge_scraping/rds_utils.py
  judge_scraping/test_judge_scraping.py
  pipeline/etl.py
  pipeline/load.py
  xml_extraction/get_unique_xml.py
  xml_extraction/metadata_xml.py
  xml_extraction/parse_xml.py
  xml_extraction/test_parse_xml.py
Labels: bug, enhancement

#131 Add dummy judge
  database/schema.sql
  database/seed_db.sql
  database/setup_reset.sh
  pipeline/load.py
Labels: enhancement

#137 Improve XML extraction
  xml_extraction/get_unique_xml.py
  xml_extraction/metadata_xml.py
  xml_extraction/parse_xml.py
  xml_extraction/test_parse_xml.py
Labels: enhancement

#141 Add etl dockerfile
  gpt/requirements.txt
  pipeline/build_push_dockerfile.sh
  pipeline/dockerfile
  pipeline/requirements.txt
Labels: AWS, docker

#163 Create bash script and update readme for email
  README.md
  email/Dockerfile
  email/README.md
  email/build_push_dockerfile.sh
  email/requirements.txt
Labels: enhancement, AWS
